### ISSUE TITLE
Profanity in codebase

### ISSUE THREAD

**Issue by fgeek** [cybercom-finland/there#1]
It might be a good idea not to use profanity in codebase at all. Example: https://github.com/cybercom-finland/there/blob/master/src/cli/there#L582

**Comment by jaskakivela** [comment]
On 03/04/15 21:51, Henri Salo wrote:

> It might be a good idea not to use profanity in codebase at all.
> Example:
> https://github.com/cybercom-finland/there/blob/master/src/cli/there#L582

It's open source. Fix it and stop complaining. Thanks.

```
-jk
```

## 

Nam in omnibus fere minus valent praecepta quam experimenta. -Quintilian

Jaska Kivelä    | Cybercom Finland      | gsm   040 576 2988
jk@cybercom.com | Pakkahuoneenaukio 2 A | https://keybase.io/jaska
specialist      | PL 13, 33201 TAMPERE  | OCP - RHCE - JNCIA

**Comment by fgeek** [comment]
It wasn't a complaint.

**Comment by jaskakivela** [comment]
On 03/04/15 23:56, Henri Salo wrote:

> It wasn't a complaint.

Then what was it?

## 

Nam in omnibus fere minus valent praecepta quam experimenta. -Quintilian

Jaska Kivelä    | Cybercom Finland      | gsm   040 576 2988
jk@cybercom.com | Pakkahuoneenaukio 2 A | https://keybase.io/jaska
specialist      | PL 13, 33201 TAMPERE  | OCP - RHCE - JNCIA

**Comment by fgeek** [comment]
Suggestion for improvement. There is no tags or similar in GitHub (users can't add/edit labels). If you think it should not be changed then just close this item in tracker.

**Comment by jaskakivela** [comment]
commit 12dd4a0c07700e9f8dff53479284f1ac5a3aaa63
Author: Jaska Kivelä jk@ostovoima.kivela.net
Date:   Mon Apr 6 19:27:02 2015 +0300

```
Reducing profanity in codebase. https://github.com/cybercom-finland/there/issues/1
```

**Comment by jaskakivela** [comment]
Better now?
